### ISSUE TITLE
Crashed site after plug in update Google Analytics Dashboard for WP (GADWP)

### ISSUE THREAD

**Issue by brookeroth** [awesomemotive/exactmetrics-repo#1]
Updated the plug in : Google Analytics Dashboard for WP (GADWP) and it crashed my site giving me the error 500 page. 

we work on wordpress.org and my site completely crashed after updating the plug in.

**Comment by chriscct7** [comment]
I would recommend getting in touch with our support team at ExactMetrics.com/lite-support/ as they will need a copy of your server error logs to know exactly what happened.
